version: "3.9"
services:

  redis:
    image: redis
    hostname: ${REDIS_HOST:-redis}
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT:-6379}:6379
    command: redis-server --appendonly yes --dir "/data"

  mongo:
    image: mongo
    hostname: ${MONGO_HOST:-mongo}
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGO_PORT:-27017}:27017

volumes:
  redis_data:
  mongo_data:
