version: "3.9"
services:

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --dir "/data"
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    ports:
      - "27017:27017"

volumes:
  redis_data:
  mongo_data:
