export const SECRET = 'SESSION_SECRET';
export const STORAGE_PREFIX = 'SESSION_STORAGE_PREFIX';
export const STORAGE_USER_KEY = 'SESSION_STORAGE_USER_KEY';
export const STORAGE_SHADOW_KEY = 'SESSION_STORAGE_SHADOW_KEY';
export const COOKIE_SECURE = 'SESSION_COOKIE_SECURE';
export const COOKIE_HTTPONLY = 'SESSION_COOKIE_HTTPONLY';
export const COOKIE_MAX_AGE = 'SESSION_COOKIE_MAX_AGE';

export default [
  SECRET,
  STORAGE_PREFIX,
  STORAGE_USER_KEY,
  STORAGE_SHADOW_KEY,
  COOKIE_SECURE,
  COOKIE_HTTPONLY,
  COOKIE_MAX_AGE,
];
